// Maximum Supported Loops
#define CPPCORE_LOOP_MAX 32

// CPPCORE_LOOP_COUNT must be set
#if !defined(CPPCORE_LOOP_COUNT)
#error CPPCORE_LOOP_COUNT not set
#endif

// Too Many
#if(CPPCORE_LOOP_COUNT > CPPCORE_LOOP_MAX) 
#error CPPCORE_LOOP_COUNT too big
#endif

// Define CPPCORE_LOOP_START on first iteration
#if !defined(CPPCORE_LOOP_START)
#define CPPCORE_LOOP_START 0
#endif

// Execute Loop Macro
#if defined(CPPCORE_LOOP_MACRO)
CPPCORE_LOOP_MACRO(CPPCORE_LOOP_START)
#else
#error CPPCORE_LOOP_MACRO not set
#endif

// Iterations
#if(CPPCORE_LOOP_START == 0)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 1
#elif(CPPCORE_LOOP_START == 1)
#undef CPPCORE_LOOP_START 
#define CPPCORE_LOOP_START 2
#elif(CPPCORE_LOOP_START == 2)
#undef CPPCORE_LOOP_START 
#define CPPCORE_LOOP_START 3
#elif(CPPCORE_LOOP_START == 3)
#undef CPPCORE_LOOP_START 
#define CPPCORE_LOOP_START 4
#elif(CPPCORE_LOOP_START == 4)
#undef CPPCORE_LOOP_START 
#define CPPCORE_LOOP_START 5
#elif(CPPCORE_LOOP_START == 5)
#undef CPPCORE_LOOP_START 
#define CPPCORE_LOOP_START 6
#elif(CPPCORE_LOOP_START == 6)
#undef CPPCORE_LOOP_START 
#define CPPCORE_LOOP_START 7
#elif(CPPCORE_LOOP_START == 7)
#undef CPPCORE_LOOP_START 
#define CPPCORE_LOOP_START 8
#elif(CPPCORE_LOOP_START == 8)
#undef CPPCORE_LOOP_START 
#define CPPCORE_LOOP_START 9
#elif(CPPCORE_LOOP_START == 9)
#undef CPPCORE_LOOP_START 
#define CPPCORE_LOOP_START 10
#elif(CPPCORE_LOOP_START == 10)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 11
#elif(CPPCORE_LOOP_START == 11)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 12
#elif(CPPCORE_LOOP_START == 12)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 13
#elif(CPPCORE_LOOP_START == 13)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 14
#elif(CPPCORE_LOOP_START == 14)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 15
#elif(CPPCORE_LOOP_START == 15)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 16
#elif(CPPCORE_LOOP_START == 16)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 17
#elif(CPPCORE_LOOP_START == 17)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 18
#elif(CPPCORE_LOOP_START == 18)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 19
#elif(CPPCORE_LOOP_START == 19)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 20
#elif(CPPCORE_LOOP_START == 20)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 21
#elif(CPPCORE_LOOP_START == 21)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 22
#elif(CPPCORE_LOOP_START == 22)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 23
#elif(CPPCORE_LOOP_START == 23)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 24
#elif(CPPCORE_LOOP_START == 24)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 25
#elif(CPPCORE_LOOP_START == 25)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 26
#elif(CPPCORE_LOOP_START == 26)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 27
#elif(CPPCORE_LOOP_START == 27)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 28
#elif(CPPCORE_LOOP_START == 28)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 29
#elif(CPPCORE_LOOP_START == 29)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 30
#elif(CPPCORE_LOOP_START == 30)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 31
#elif(CPPCORE_LOOP_START == 31)
#undef CPPCORE_LOOP_START
#define CPPCORE_LOOP_START 32
#endif

// Recursion or Cleanup

#if(CPPCORE_LOOP_START < CPPCORE_LOOP_COUNT)
 #include <CppCore/PreprocessorLoop.h>
#else
 #ifdef CPPCORE_LOOP_START
  #undef CPPCORE_LOOP_START
  #define CPPCORE_LOOP_START 0
 #endif
 #ifdef CPPCORE_LOOP_COUNT
  #undef CPPCORE_LOOP_COUNT
 #endif
 #ifdef CPPCORE_LOOP_MACRO
 #undef CPPCORE_LOOP_MACRO
 #endif
#endif
