#pragma once

// Version (don't add anything behind the numbers!)

#define CPPCORE_VERSION_MAJOR 1
#define CPPCORE_VERSION_MINOR 0
#define CPPCORE_VERSION_PATCH 5

// Macros

#define CPPCORE_STR_HELPER(x) #x
#define CPPCORE_STR(x) CPPCORE_STR_HELPER(x)

// Microsoft RC File Format (MAJOR,MINOR,PATCH,0)
#define CPPCORE_VERSION_RESRC CPPCORE_VERSION_MAJOR,CPPCORE_VERSION_MINOR,CPPCORE_VERSION_PATCH,0

// Strings of Version (From "MAJOR" to "MAJOR.MINOR.PATCH.0")
#define CPPCORE_VERSION_STR1 CPPCORE_STR(CPPCORE_VERSION_MAJOR)
#define CPPCORE_VERSION_STR2 CPPCORE_VERSION_STR1 "." CPPCORE_STR(CPPCORE_VERSION_MINOR)
#define CPPCORE_VERSION_STR3 CPPCORE_VERSION_STR2 "." CPPCORE_STR(CPPCORE_VERSION_PATCH)
#define CPPCORE_VERSION_STR4 CPPCORE_VERSION_STR3 ".0"
