name: Build WASI
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      MODE: release
      TARGET_OS: wasi
      TARGET_ARCH: ${{ matrix.arch }}
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022,ubuntu-22.04,macos-13]
        arch: [wasm32]
        sdk: [24]
    steps:
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v4
    
    # Install WASI SDK
    #-# name: Install WASI SDK
     # uses: cyberjunk/gha-wasi-install@main
     # with:
     #   version: 24.0

    # Install WASI SDK
    - name: Install WASI SDK
      shell: bash
      env:
        VERSIONMAJOR: ${{ matrix.sdk }}
        VERSIONMINOR: 0
        OS: macos
        ARCH: x86_64
        EXT: tar.gz
      run: |
        FILENAME=wasi-sdk-$VERSIONMAJOR.$VERSIONMINOR-$ARCH-$OS
        echo $FILENAME
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-$VERSIONMAJOR/$FILENAME.$EXT
        tar xvfz $FILENAME.$EXT
        ls -la
        echo WASI_SDK_PATH=$(pwd)/$FILENAME >> "$GITHUB_ENV"

    # TEST
    - name: TEST
      run: |
        echo $ImageOS
        echo $WASI_SDK_PATH
        ls -la $WASI_SDK_PATH
        $WASI_SDK_PATH/bin/clang --version

    # Build
    - name: Build
      run: |
        make -j${{ env.JOBS }}

    # Test
    #- name: Test
    #  run: make test
