name: Build WASI
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      MODE: release
      TARGET_OS: wasi
      TARGET_ARCH: ${{ matrix.arch }}
      TARGET_CPUREV: ${{ matrix.cpurev }}
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13,macos-14]
        arch: [wasm32]
        cpurev: [default]
    steps:
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v4
      
    # TEST
    - name: TEST
      run: echo $WASI_SDK_PATH
      
    # Install WASI
    - name: Install WASI
      env:
        VERSIONMAJOR: 24
        VERSIONMINOR: 0
        OS: macos
        ARCH: x86_64
        EXT: tar.gz
      run: |
        FILENAME=wasi-sdk-$VERSIONMAJOR.$VERSIONMINOR-$ARCH-$OS
        echo $FILENAME
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-$VERSIONMAJOR/$FILENAME.$EXT
        tar xvfz $FILENAME.$EXT
        ls -la
        echo WASI_SDK_PATH=$(pwd)/$FILENAME >> "$GITHUB_ENV"

    # TEST
    - name: TEST
      run: |
        echo $WASI_SDK_PATH
        ls -la $WASI_SDK_PATH
