name: Build Android
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      MODE: release
      TARGET_OS: android
      TARGET_ARCH: ${{ matrix.arch }}
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019,macos-11]
        arch: [x64,x86,arm64,arm]
        ndk: [r25b]
    steps:
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v3

    # Build
    - name: Build
      run: make -j${{ env.JOBS }}

    # Test
    # Note: x64 and x86 require VT-x on Windows.
    # But it is disabled on Github Hyper-V runners.
    - name: Test
      if: matrix.os != 'windows-2019' || (matrix.arch != 'x64' && matrix.arch != 'x86')
      env:
        ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 10
      run: make test
