name: Build Android
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      MODE: release
      TARGET_OS: android
      TARGET_ARCH: ${{ matrix.arch }}
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019,macos-11]
        arch: [x64,x86,arm64,arm]
        ndk: [r25b]
    steps:
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v3

    # Android NDK
    - name: Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      timeout-minutes: 10
      with:
        ndk-version: ${{ matrix.ndk }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: ANDROID_HOME (WIN)
      if: ${{ matrix.os }} == 'windows-2019'
      run: echo $env:ANDROID_HOME

    - name: ANDROID_HOME (WIN)
      if: ${{ matrix.os }} == 'macos-11'
      run: echo $ANDROID_HOME

    # Build
    - name: Build
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: make -j${{ env.JOBS }}
