name: Build WASI
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      MODE: release
      TARGET_OS: wasi
      TARGET_ARCH: ${{ matrix.arch }}
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019,windows-2022,ubuntu-20.04,ubuntu-22.04,ubuntu-24.04,macos-12,macos-13,macos-14,macos-15]
        arch: [wasm32]
        sdk: [24]
    steps:
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v4
    
    # Install WASI SDK
    #-# name: Install WASI SDK
     # uses: cyberjunk/gha-wasi-install@main
     # with:
     #   version: 24.0
    
    # Install WASI SDK
    - name: Install WASI SDK
      shell: bash
      env:
        VERSIONMAJOR: ${{ matrix.sdk }}
        VERSIONMINOR: 0
        EXT: tar.gz
      run: |
        echo Installing on: $ImageOS
        if [ $ImageOS == macos12 ] || [ $ImageOS == macos13 ]; then \
          OS=macos; \
          ARCH=x86_64; \
        elif [ $ImageOS == macos14 ] || [ $ImageOS == macos15 ]; then \
          OS=macos; \
          ARCH=arm64; \
        elif [ $ImageOS == ubuntu20 ] || [ $ImageOS == ubuntu22 ] || [ $ImageOS == ubuntu24 ]; then \
          OS=linux; \
          ARCH=x86_64; \
        elif [ $ImageOS == win19 ] || [ $ImageOS == win22 ]; then \
          OS=windows; \
          ARCH=x86_64; \
        else \
          echo UNKNOWN OPERATING SYSTEM; \
          exit 1; \
        fi
        FILENAME=wasi-sdk-$VERSIONMAJOR.$VERSIONMINOR-$ARCH-$OS
        URL=https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-$VERSIONMAJOR/$FILENAME.$EXT
        curl -L -O $URL
        tar xvfz $FILENAME.$EXT
        echo WASI_SDK_PATH=$(pwd)/$FILENAME >> "$GITHUB_ENV"

    - name: Install Wasmer
      uses: wasmerio/setup-wasmer@v3.1
      with:
        version: '4.4.0'

    # Clang Version
    - name: Clang Version
      shell: bash
      run: |
        $WASI_SDK_PATH/bin/clang --version

    # Wasmer Version
    - name: Wasmer Version
      shell: bash
      run: |
        wasmer --version

    # Build
    - name: Build
      run: |
        make -j${{ env.JOBS }}

    # Test
    #- name: Test
    #  run: make test
