name: Build Android
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      MODE: release
      TARGET_OS: android
      TARGET_ARCH: ${{ matrix.arch }}
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019,macos-11]
        arch: [x64,x86,arm64,arm]
        ndk: [r25b]
    steps:
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v3

    # Android NDK
    - name: Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      timeout-minutes: 10
      with:
        ndk-version: ${{ matrix.ndk }}

    # Build
    - name: Build
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: make -j${{ env.JOBS }}
