name: Build WASI
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      MODE: release
      TARGET_OS: wasi
      TARGET_ARCH: ${{ matrix.arch }}
      TARGET_CPUREV: ${{ matrix.cpurev }}
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13,macos-14]
        arch: [wasm32]
        cpurev: [default]
    steps:
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v4
